theme: jekyll-theme-minimal
title: Samuel Häfner
description: University of St. Gallen
logo: portrait.png
email: samuel.haefner@unisg.ch
linkedin: www.linkedin.com/in/samuel-häfner-42246312
google_analytics: G-BFYL5LPRVJ
